name: jack_api
description: Flutter package for api source and network on the top of Dio package
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cryptography:
  dio: ^5.4.1
  dio_http2_adapter:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs:
  path_provider: 2.1.2
  pretty_dio_logger:

dev_dependencies:
  build_runner:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator:
  lints: ^3.0.0

flutter:
