name: jack_api
description: Flutter package for api source and network on the top of Dio package
version: 0.0.1
homepage:

environment:
    sdk: ">=3.0.3 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    cryptography: ^2.5.0
    cryptography_flutter: ^2.3.0
    dio: ^5.2.1+1
    dio_http2_adapter: ^2.3.0
    flutter:
        sdk: flutter
    get_it: ^7.6.0
    isar: ^3.1.0+1
    isar_flutter_libs: ^3.1.0+1
    path_provider: ^2.0.15
    pretty_dio_logger: ^1.3.1

dev_dependencies:
    build_runner: ^2.4.6
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    isar_generator: ^3.1.0+1
    lints: ^2.1.1

flutter:
